server:
  port: 8080
sharding:
  jdbc: 
    driverClassName: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 100
    initialSize: 1
    maxWait: 15000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 30000
    minEvictableIdleTimeMillis: 180000
    validationQuery: SELECT 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    removeAbandoned: true
    removeAbandonedTimeout: 600
    logAbandoned: false
    connectionInitSqls: 
    
    masterUrl0: jdbc:mysql://192.168.56.75:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    masterUsername0: yinsl
    masterPassword0: Abcd_1234!
    
    masterUrl1: jdbc:mysql://192.168.56.76:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    masterUsername1: yinsl
    masterPassword1: Abcd_1234!
    
    slaveUrl0: jdbc:mysql://192.168.56.73:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    slaveUsername0: yinsl
    slavePassword0: Abcd_1234!
    
    slaveUrl1: jdbc:mysql://192.168.56.74:3306/test?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&failOverReadOnly=false
    slaveUsername1: yinsl
    slavePassword1: Abcd_1234!
spring:
  redis:
    host: 192.168.56.75
    port: 6379